### ISSUE TITLE
Page content shifted to left in the mobile view and the tablet view

### ISSUE THREAD

**Issue by rohit-raje-786** [fossasia/open-event-webapp#2532]
**Actual Behaviour**

At the window size the content is align perfectly.But at the mobile and the tablet view the content is shifted to left side which doesn't look good

**Expected Behaviour**

When we move on to the mobile view or the tablet view the content should align perfectly in the middle of the page layout.

**Steps to reproduce it**

Working on the css part will help to resolve this issue, making it more responsive through adding css flexbox.

**Log for the issue**

It's not a bug.

**Screenshots of the issue**

At window view:
![image](https://user-images.githubusercontent.com/61861303/111896986-5943f580-8a43-11eb-9512-c446e32fb676.png)

At mobile view:
![image](https://user-images.githubusercontent.com/61861303/111897003-77115a80-8a43-11eb-9cbc-2cab90f89547.png)

**Would you like to work on the issue?**

Yes, I would love to work on this issue.

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me to get started?

**Comment by prsmahajan** [comment]
Hi, I have solved the issue of token no #2532. You can just check it out on my repo [https://github.com/prsmahajan/open-event-wsgen](url)

**Comment by prsmahajan** [comment]
Actually I don't know how to merge this problem in fossasia codebase but I tried my best :)

**Comment by rohit-raje-786** [comment]
I have already solve the problem.don’t waste your time on the issue that
are already resolved.

**Comment by prsmahajan** [comment]
The problem was not resolved, I pulled the codebase on my local machine that's why i resolved it.

**Comment by prsmahajan** [comment]
If you have resolved it then kindly close the issue, this confuses other contributers

**Comment by kant18** [comment]
Hlo sir,
I want to solve  this  issue  and i think  i may do this.

**Comment by shrutibhardwaj22** [comment]
I want to work on this issue. please assign me this issue
